name = "aiken-lang/acca"
version = "0.0.1"
licences = ["MIT"]
description = "The Aiken Non Standard Library"

dependencies = [
  { name = "aiken-lang/stdlib", version = "1e82ccd5d30d68615b6c0f3b84947b5e93f23549", source = "github" }
]

[repository]
user = "Cardano-Fans"
project = "acca"
platform = "github"
